export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const TWITTER_LOGIN = 'TWITTER_LOGIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const EXAMPLE = 'EXAMPLE';
export const EXAMPLE_TWO = 'EXAMPLE-TWO';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
