export const EXAMPLE = 'EXAMPLE';
export const EXAMPLE_TWO = 'EXAMPLE_TWO';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const CLEAR_FLASH_MESSAGES = 'CLEAR_FLASH_MESSAGES';
export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
