export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const CLEAR_FLASH_MESSAGES = 'CLEAR_FLASH_MESSAGES';
export const BOOKMARK_ARTICLE = 'BOOKMARK_ARTICLE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';